# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('count_season', models.PositiveIntegerField(default=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('baseperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.BasePeriod')),
                ('season', models.PositiveIntegerField(default=1)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('contract.baseperiod',),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('start', 'end')]),
        ),
        migrations.AddField(
            model_name='baseperiod',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contract.baseperiod_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='period',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract'),
        ),
    ]
