# Generated by Django 2.1.7 on 2019-03-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('count_saison', models.PositiveIntegerField(default=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contract_template.contracttemplate_set+', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('season', models.PositiveIntegerField(default=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_template.ContractTemplate')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contract_template.period_set+', to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('start', 'end')},
        ),
        migrations.AlterUniqueTogether(
            name='contracttemplate',
            unique_together={('start', 'end')},
        ),
    ]
