# Generated by Django 2.1.7 on 2019-03-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracttemplate',
            old_name='count_saison',
            new_name='count_season',
        ),
    ]
